<?php
/**
 * Segment.io
 *
 * @category    Segment.io Ext
 * @package     Segmentio_Segmentio
 * @author      Segment.io
 * @copyright   Copyright © 2014 Segment.io
 */
?>
<?php if (Mage::getStoreConfig('segmentio_segmentio/general/active')):?>
    <?php $product = Mage::registry('product'); ?>

    <script type="text/javascript">
    //<![CDATA[
        analytics.track('Viewed Product', {
            id: '<?php echo $product->getId()?>',
            sku: '<?php echo $product->getSku()?>',
            name: '<?php echo $product->getName()?>',
            price: '<?php echo $product->getFinalPrice()?>',
            category: '<?php echo Mage::helper('segmentio_segmentio')->getCategoryItemProduct($product->getId())?>'
        });
    //]]>
    </script>
<?php endif; ?>
