<?php
/**
 * Segment.io
 *
 * @category    Segment.io Ext
 * @package     Segmentio_Segmentio
 * @author      Segment.io
 * @copyright   Copyright © 2014 Segment.io
 * @var $this Atwix_Segmentio_Block_Track
 */

?>
<?php if (Mage::getStoreConfig('segmentio_segmentio/general/active')): ?>


        <?php foreach($this->getTrackSession() as $key => $value):?>
            <?php $this->unsetSessionData($key); ?>
            <?php if ($value) : ?>
                <script type="text/javascript">
                //<![CDATA[
                      analytics.track('<?php echo $value['event']; ?>', {
                      id: '<?php echo $value['id']; ?>',
                      sku: '<?php echo $value['sku']; ?>',
                      name: '<?php echo $value['name']; ?>',
                      price: '<?php echo $value['price']; ?>',
                      category: '<?php echo $value['category']; ?>'
                  });
                //]]>
                </script>
            <?php endif; ?>
        <?php endforeach; ?>

<?php endif; ?>