<?php
/**
 * Segment.io
 *
 * @category    Segment.io Ext
 * @package     Segment_Analytics
 * @author      Segment.io
 * @copyright   Copyright © 2014 Segment.io
 * @var $this   Segment_Analytics_Block_Onepage_Success
 */
?>
<?php if(Mage::getStoreConfig('segment_analytics/general/active')):?>
    <?php
    $orderIds = $this->getOrderId();
    $collection = $this->getOrderCollection($orderIds);
    $orderInformation = $this->getOrderInfo($collection);
    ?>

    <script id="segmentio-analytics-order" type="text/javascript">
        //<![CDATA[
        analytics.track('Completed Order', {
            <?php
                $subgect =  json_encode($orderInformation['orderInfo']);
                $orderInfo = preg_replace('(\{)', "", $subgect );
                $orderInfo = preg_replace('(\})', "", $orderInfo );
                echo $orderInfo;
                echo ",\n";
            ?>
            products:[
                <?php foreach ($orderInformation['productItem'] as $productItem) {
                        echo json_encode($productItem);
                       echo ",";
                }
                ?>
            ]
        });
        //]]>
    </script>
<?php endif; ?>