<?php
/**
 * Segment.io
 *
 * @category    Segment.io Ext
 * @package     Segment_Analytics
 * @author      Segment.io
 * @copyright   Copyright © 2014 Segment.io
 * @var $this Segment_Analytics_Block_Init
 */
?>
<?php if (Mage::getStoreConfig('segment_analytics/general/active')): ?>
    <script id="segmentio-analytics-init" type="text/javascript">
    //<![CDATA[
        window.analytics||(window.analytics=[]),window.analytics.methods=[
            "identify","track","trackLink","trackForm","trackClick","trackSubmit",
            "page","pageview","ab","alias","ready","group","on","once","off"
        ],window.analytics.factory=function(t){
            return function(){
                var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics
            }
        };
        for(var i=0;i<window.analytics.methods.length;i++){
            var method=window.analytics.methods[i];
            window.analytics[method]=window.analytics.factory(method)
        } window.analytics.load=function(t){
            var a=document.createElement("script");
            a.type="text/javascript",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+
                "d2dq2ahtl5zl1z.cloudfront.net/analytics.js/v1/"+t+"/analytics.min.js";
            var n=document.getElementsByTagName("script")[0];
            n.parentNode.insertBefore(a,n)
        }, window.analytics.SNIPPET_VERSION="2.0.8",
        window.analytics.load("<?php echo Mage::getStoreConfig('segment_analytics/general/segment_key') ?>");
        <?php if (Mage::registry('current_category')): ?>
            window.analytics.page('Category','<?php echo Mage::registry('current_category')->getName()?>');
        <?php else:?>
            window.analytics.page();
        <?php endif; ?>
    //]]>
    </script>

    <?php $userData = json_encode($this->getUserData()); ?>
        <?php if ($this->getUserId()) : ?>
            <script id="segmentio-analytics-identify" type="text/javascript">
                //<![CDATA[
                var segmCustomerId = 'id_' + '<?php echo $this->getUserId(); ?>';
                analytics.identify(segmCustomerId, <?php echo $userData ?>);
                analytics.track('Registered');
                //]]>
            </script>
        <?php endif; ?>
<?php endif; ?>