<?php
/**
 * Segment.io
 *
 * @category    Segment.io Ext
 * @package     Segment_Analytics
 * @author      Segment.io
 * @copyright   Copyright © 2014 Segment.io
 */
?>
<?php if (Mage::getStoreConfig('segment_analytics/general/active')):?>
    <?php $product = Mage::registry('product'); ?>
    <?php $productData = json_encode(Mage::helper('segment_analytics')->getProductData($product)); ?>

    <script id="segmentio-analytics-product" type="text/javascript">
    //<![CDATA[
        analytics.track('Viewed Product', <?php echo $productData ?>);
    //]]>
    </script>
<?php endif; ?>
