<?php    
    throw new Exception("Not used anymore, look at page.phtml");
    echo $this->getLayout()->createBlock('segment_analytics/json')
    ->setData($this->getData())
    ->setVarName('segment_analytics_category')
    ->toHtml();
?>
<script type="text/javascript">
    if(segment_analytics_category.category_child)
    {
        analytics.page(segment_analytics_category.category_parent);
    }
    else
    {
        analytics.page(segment_analytics_category.category_parent);
    }    
</script>