<?php
    echo $this->renderDataAsJsonVar('segment_analytics_identity');
?>
<script type="text/javascript">
    var segment_analytics_identity_to_send = {};
    for(index in segment_analytics_identity)
    {
        if(!segment_analytics_identity.hasOwnProperty(index)) { continue; }
        if(['user_id','key'].indexOf(index) !== -1 ){ continue; }
        segment_analytics_identity_to_send[index] = segment_analytics_identity[index];
    }
    analytics.identify(segment_analytics_identity.user_id, 
    segment_analytics_identity_to_send);
    
</script>