<?php
/**
 * Atwix
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.

 * @category    Atwix Ext
 * @package     Atwix_Segmentio
 * @author      Atwix Core Team
 * @copyright   Copyright (c) 2014 Atwix (http://www.atwix.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if (Mage::getStoreConfig('atwix_segmentio/general/active')):?>
    <?php $product = Mage::registry('product'); ?>

    <script type="text/javascript">
    //<![CDATA[
        analytics.track('Viewed Product', {
            id: '<?php echo $product->getId()?>',
            sku: '<?php echo $product->getSku()?>',
            name: '<?php echo $product->getName()?>',
            price: '<?php echo $product->getFinalPrice()?>',
            category: '<?php echo Mage::helper('atwix_segmentio')->getCategoryItemProduct($product->getId())?>'
        });
    //]]>
    </script>
<?php endif; ?>
