<?php
/**
 * Atwix.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.

 * @category    Atwix Ext
 * @package     Atwix_Segmentio
 * @author      Atwix Core Team
 * @copyright   Copyright (c) 2014 Atwix (http://www.atwix.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @var $this Atwix_Segmentio_Block_Track
 */

?>
<?php if (Mage::getStoreConfig('atwix_segmentio/general/active')): ?>


        <?php foreach($this->getTrackSession() as $key => $value):?>
            <?php $this->unsetSessionData($key); ?>
            <?php if ($value) : ?>
                <script type="text/javascript">
                //<![CDATA[
                      analytics.track('<?php echo $value['event']; ?>', {
                      id: '<?php echo $value['id']; ?>',
                      sku: '<?php echo $value['sku']; ?>',
                      name: '<?php echo $value['name']; ?>',
                      price: '<?php echo $value['price']; ?>',
                      category: '<?php echo $value['category']; ?>'
                  });
                //]]>
                </script>
            <?php endif; ?>
        <?php endforeach; ?>

<?php endif; ?>